[package]
name = "api_db"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
api_db_macros = { path = "../api_db_macros" }
db_pool = { path = "../db_pool" }
sqlx.workspace = true
futures.workspace = true
anyhow.workspace = true
uuid.workspace = true
url.workspace = true
email_address.workspace = true
tracing.workspace = true
tokio.workspace = true
