load("//tools:defs.bzl", "cached_check")
load("//tools/nativelink:busybox.bzl", "busybox")
load("//tools/nativelink:rootfs.bzl", "busybox_rootfs")

busybox(
    name = "busybox",
    crane = "//third_party/crane:crane[crane]",
    image = "busybox:1.38.0-musl@sha256:8635836765b0c4c43970660219739baa58b0883c2e429e4b8918f7dd1519455c",
)

cached_check(
    name = "busybox_test",
    exe = "//tools:py",
    srcs = [
        "busybox_test.py",
        ":busybox",
    ],
)

busybox_rootfs(
    name = "rootfs",
    busybox = ":busybox",
)

cached_check(
    name = "rootfs_test",
    exe = "//tools:py",
    srcs = [
        "busybox_rootfs_test.py",
        ":rootfs",
    ],
)
