load(":defs.bzl", "cached_check")

command_alias(
    name = "py",
    exe = "//third_party/python:cpython[bin/python3]",
    visibility = ["PUBLIC"],
)

export_file(
    name = "agent_action_guard_src",
    src = "agent_action_guard.py",
)

command_alias(
    name = "agent_action_guard",
    exe = ":py",
    args = ["$(location :agent_action_guard_src)"],
    visibility = ["PUBLIC"],
)

cached_check(
    name = "py_version_check",
    args = [
        "-c",
        "import sys; assert sys.version_info[:3] == (3, 12, 13), sys.version; open(sys.argv[1], 'w').write('ok')",
    ],
    exe = ":py",
)
