load(":defs.bzl", "cached_check", "tree_tool")

tree_tool(
    name = "py",
    path = "bin/python3",
    tree = "//third_party/python:cpython",
    visibility = ["PUBLIC"],
)

export_file(
    name = "agent_action_guard_src",
    src = "agent_action_guard.py",
)

command_alias(
    name = "agent_action_guard",
    exe = ":py",
    args = ["$(location :agent_action_guard_src)"],
    visibility = ["PUBLIC"],
)

cached_check(
    name = "py_version_check",
    exe = ":py",
    srcs = [
        "py_version_check.py",
        "//third_party/python:pin",
    ],
)
