name: auto-queue
on:
  pull_request:
    types: [labeled, edited]
permissions:
  contents: write
  pull-requests: write
jobs:
  auto-queue:
    runs-on: ubuntu-latest
    if: >-
      contains(github.event.pull_request.labels.*.name, 'merge') && github.event.pull_request.base.ref == 'master'
    steps:
      - name: Add to merge queue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.number }}
        run: gh pr merge "$PR" --repo "$GITHUB_REPOSITORY" --auto
